### ISSUE TITLE
 It seems that you abandon the `BoostNote.next-local`，update less frequency than the cloud recently.

### ISSUE THREAD

**Issue by mokeyish** [BoostIO/BoostNote.next-local#5]
It is very important to have full control of the note data to me. Luckly I find another note taking software：https://obsidian.md .

**Comment by Komediruzecki** [comment]
Hi, mokeyish,

I didn't totally understand your question, the boost note local is not abandoned, it is left to the open source community to take care of (including me).

If you have any features/requests or questions please feel free to notify me (or post here).

Obsidian is very nice but I prefer boost note because it offers a bit more and I plan to add few neat feature along the way to make it even better.

**Comment by mokeyish** [comment]
Looking forward to your roadmap for the boost note local .
