### ISSUE TITLE
Notes missing in latest version

### ISSUE THREAD

**Issue by genericgithubuser** [BoostIO/BoostNote.next-local#6]
I am on linux, and installed 
Boost Note 0.21.1 (local)
as I was looking to upgrade from 
Boost Note 0.19.0.  

I only use local storage, but in 0.21.1 local version, I see random notes are from the left-side view.  If I open 0.19.0, it shows the notes just fine.  Oddly if I search for the note, it shows it in the search, and can open.  It sees the correct path at the top of the window for the breadcrumb view, but the left panel still does not show the page consistently.  I Installe dmatching versions on a second home system, and pointed it to the same file store, and it behaves the same, with 0.21.1 not showing the same files (but able to search/display them), while 0.19.0 shows them correctly.

**Comment by genericgithubuser** [comment]
0.19.0
![image](https://user-images.githubusercontent.com/14870210/129779334-e59dea81-d05a-4cd1-9871-f78c6d507fbc.png)

0.21.1
![image](https://user-images.githubusercontent.com/14870210/129779417-3e270f60-7731-4368-a5e9-e267aa77cda1.png)


This happens for seemingly random files, but again, if I search for the content, it shows up properly in the results and I can click and access the full note.  But it still does not show in the sidebar after that.

**Comment by Komediruzecki** [comment]
Hi, can you let me know of your view?

Do you use sidenav drag and drop View? Or last updated or something else?

Can you try changing the view and see if the notes appear?

Can you reproduce the issue with new notes?

Please contact me on slack if you want this resolved faster and if you can provide me some data so I can test it, there should not be any restrictions on showing the notes apart from notes being trashed/archived, can you check that the notes are not accidently in archive as well?

**Comment by genericgithubuser** [comment]
Hey Komediruzecki,
  Thanks for the reply. It was the drag and drop view. I just tried changing to other views, re-launching the app after, forcing a reload, and none of them show the missing files.  

I have not been able to reproduce this with new notes yet.  I tried creating notes with the same body, and similar names to see if it was something in the name causing the issue, but I can't reliably recreate it.  

The notes aren't archived, and if I switch back to the older app version, it consistently shows them properly.  If I create a new note, with a copy of the text, the new note shows up fine.  If I look at the underlying json file properties and content, they look identical other than the _id difference, so I'm not sure what to look.

**Comment by Komediruzecki** [comment]
Hi,

It would be of great help if you can provide me with the boostnote.json file, this is where you should look for any errors regarding note mappings, and folder mappings.

Does the note json file include correct folder pathnames?

If you could share those files for me to test it would be great, you can strip it down or remove content if need, or send me privately on slack.

Please backup your data before and if needed change confidential content information on a backup, which you can then send me.

Also try looking at dev console, there might be some errors there, can you screenshot the console?

**Comment by Komediruzecki** [comment]
Also, one additional thing somes to mind, can you screenshot space preferences of space tab in older version showing storage location? It could be that you are just looking at two different spaces altogether, maybe local storage in Old app and file system in new?

**Comment by genericgithubuser** [comment]
Yes, the missing note includes the folder pathname.  We know that across both versions they are looking at the identical target since searching for notes has the missing note show in the search result with the correct path.  If I add new notes, they show up just fine.  Since the 0.21.1 version didn't see the "AWS Cloudwatch" note, I added a new note with the same name.  Now, 0.19.0 sees two "AWS Cloudwatch" notes, and version 0.21.1 just sees the one still.  I copied the contents into a new note (AWS Cloudwatch2) and replaced the text in both versions of the AWS Cloudwatch file with just "zzzzz".  If I grep for zzzzz in the notes file, the two matched files look almost identical.  

`notes/lC2EfKHNyz.json:{"_id":"note:lC2EfKHNyz","title":"AWS Cloudwatch","content":"zzzzz","tags":[],"folderPathname":"/AWS","data":{},"createdAt":"2021-08-18T05:02:49.711Z","updatedAt":"2021-08-18T10:20:36.830Z","trashed":false,"_rev":"0-R-Mo53t"}
notes/Sj8vMsPAQA.json:{"_id":"note:Sj8vMsPAQA","title":"AWS Cloudwatch","content":"zzzzz","tags":[],"folderPathname":"/AWS","data":{},"createdAt":"2021-08-11T19:08:46.019Z","updatedAt":"2021-08-18T10:20:31.203Z","trashed":false,"_rev":"hWZd4zBqE"}
`

Since both 19 and 21 show the updated files, with 21 just always missing some seemingly random notes.

19
![image](https://user-images.githubusercontent.com/14870210/129884084-32229008-e900-4ca5-969e-d055d5b4c3fb.png)

21
![image](https://user-images.githubusercontent.com/14870210/129884196-a1992b56-7f5e-43e6-bb75-122c4ee31d0b.png)

**Comment by Komediruzecki** [comment]
It's really interesting issue,

Yeah, I would need boostnote.json to see if everything fits, you can strip it down to just this folder, what I would like to see is:
![image](https://user-images.githubusercontent.com/18196945/129906843-e7ab2d9d-98fd-4316-be13-1d9b0a45c501.png)

Because ordered Ids/orderId is what keeps info on what to show in sidenav, but this is used only on Drag and Drop view 
![image](https://user-images.githubusercontent.com/18196945/129906967-ab7a2899-ce96-4e43-bd04-4a906c6bd082.png)

But on other sortings it should basically shown them anyways.

Your data looks clean, no problems like you said, I am almost certain boostnote.json is valid as well so we might have a weird issue here.

But if you can get me that part of boostnote.json it would be great.

We can also debug this further via console, you could put a breakpoint into source and see what does sidenav sees when mapping the data: 

See image for clarification:
You need to go to sources tab, open the sidebarTree.tsx (mapper) and on line 524 put a breakpoint, there you could inspect tree (but you can see top level + one level below of items)

If the list of notes in AWS folder is included, then this is a very weird issue, if not, you could go further to inspect why it is not included.

![SourceDebug](https://user-images.githubusercontent.com/18196945/129908251-537d86d3-90d7-4d15-ad28-0af2ca959792.png)

**Comment by genericgithubuser** [comment]
Thanks for the detail!  That was amazingly useful.  
Okay, so boostnote.json actually is missing the entry to the "missing" note in the orderedIds list for that folder.  I have no idea how .19 shows it, even after restarts and re-launches.  I guess search might actually look inside the notes folder since the file exists and is healthy, so that is why search works.  So at least why it's not showing in 21 makes sense, and why 21 seemed to not be showing errors.  I guess the only question left is... is there a way I can get boost to re-scan that notes directory and re-build the boostnote.json?

**Comment by Komediruzecki** [comment]
Hi,

the reasons of why it wasn't included is a mystery but it is very interesting for me to inspect since it might happen to someone else.

In fact, YES, you can rescan everything, boost note latest version will look for: 'orderedIds' if the list is missing it will recreate it - hopefully adding the notes you were missing in the first place, but if it happens again it is either a bug or your note somehow breaks the code :D

How to do it:
1. Please backup your complete boostnote.json file beforehand (notes and everything would be good too)
2. Just locate the AWS folder you have problems with, in boostnote.json
3. Remove the complete entry 'orderedIds' (see image)
4. Reload or do this with the app closed and then open the application
5. Boost note will see it missing and hopefully add correct notes inside as it should in the first place
6. If it does not or something wrong happens (you can copy everything to a backup and test it there first) - please restore backed up boostnote.json
7. Fingers crossed it works, but if it does not we could catch a bug with some more insights 
8. More insights could be that you repeat this process but set a breakpoint on the code where the loading/reloading happens - this way you can see the algorithm unfold and why those notes are not added!
9. The code is stored in `src/lib/db/createStore.ts`, function `prepareStorage`

![image](https://user-images.githubusercontent.com/18196945/130095873-5eb633ab-536f-4d4d-aa26-b3371599f6bd.png)

**Comment by genericgithubuser** [comment]
Great!! That did it. There were some other folders impacted so I went through and deleted the orderIds section for each section, and now everything shows normally.  I'll definitely keep my eye on it to make sure I don't see this reoccur, and will reference some of the insight you've given for some more in depth troubleshooting if it does.  Thanks for all the help!!

**Comment by Komediruzecki** [comment]
I am glad it worked,

I can see this happening only in the sense if you installed one version of the app then another and something got mixed up or if the boostnote.json somehow already got the 'orderedIds' for the folder beforehand, anyways, I think this can be a great solution for anyone else experiencing similar issues so if someone has similar problem, let me know.

Thank you for the feedback and patience, if you have any other questions, please don't hesitate to ask!
